server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: "example-ms"

logging:
  file:
    path: ${LOG_PATH:/tmp}

management:
  endpoints:
    web:
      cors:
        allowed-origins: ${ALLOWED_ORIGINS:https://localhost}
      exposure:
        include: [health, info, prometheus]
  server:
    port: 9081

---

spring:
  profiles: default

---